/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sogou_nlu_clivia_commons_encrypt_EncryptFacade */

#ifndef _Included_com_sogou_nlu_clivia_commons_encrypt_EncryptFacade
#define _Included_com_sogou_nlu_clivia_commons_encrypt_EncryptFacade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sogou_nlu_clivia_commons_encrypt_EncryptFacade
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sogou_nlu_clivia_commons_encrypt_EncryptFacade_encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sogou_nlu_clivia_commons_encrypt_EncryptFacade
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sogou_nlu_clivia_commons_encrypt_EncryptFacade_decrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
